### ISSUE TITLE
maxpeers in wrong heimdall configuration file ?

### ISSUE THREAD

**Issue by aujl** [CryptoManufaktur-io/polygon-docker#1]
These parameters should be configured in Heimdall's `config.toml ` and not in the `heimdall-config.toml `configuration file.

https://github.com/CryptoManufaktur-io/polygon-docker/blob/5f857c18aa0b3402e24ceef7df7accac2f3378f0/polygon/docker-entrypoint-heimdalld.sh#L52

**Comment by yorickdowne** [comment]
Thanks, will take a look

**Comment by yorickdowne** [comment]
Well spotted. Will be fixed Soon(tm)
