### ISSUE TITLE
unstable replacement

### ISSUE THREAD

**Issue by aujl** [CryptoManufaktur-io/polygon-docker#2]
there's several occurrences of `laddr =` in different sections. 
Better make sure that it is indeed the `laddr = `of the `[rpc] `dictionary that is modified?

https://github.com/CryptoManufaktur-io/polygon-docker/blob/5f857c18aa0b3402e24ceef7df7accac2f3378f0/polygon/docker-entrypoint-heimdalld.sh#L47

**Comment by yorickdowne** [comment]
Thanks, will take a look

**Comment by yorickdowne** [comment]
That would require dasel or something like it, that understands toml. I'm not saying "no", but since the 26657 works right now, even if it's a little brittle, I'll push this.

Thanks for caring!

**Comment by yorickdowne** [comment]
dasel is in. Thanks again!
